<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mod_level extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get leveluser by idleveluser
     */
    function get_leveluser($idleveluser)
    {
        return $this->db->get_where('leveluser',array('idleveluser'=>$idleveluser))->row_array();
    }
        
    /*
     * Get all leveluser
     */
    function get_all_leveluser()
    {
        $this->db->order_by('idleveluser', 'desc');
        return $this->db->get('leveluser')->result_array();
    }
        
    /*
     * function to add new leveluser
     */
    function add_leveluser($params)
    {
        $this->db->insert('leveluser',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update leveluser
     */
    function update_leveluser($idleveluser,$params)
    {
        $this->db->where('idleveluser',$idleveluser);
        return $this->db->update('leveluser',$params);
    }
    
    /*
     * function to delete leveluser
     */
    function delete_leveluser($idleveluser)
    {
        return $this->db->delete('leveluser',array('idleveluser'=>$idleveluser));
    }
}